//
//  Descriptions.swift
//  VVVV2ID
//
//  Created by Antonio Romano on 10/12/21.
//

//EVANGELION
var evangelionDescription = "In the year 2015, the world stands on the brink of destruction. Humanity's last hope lies in the hands of Nerv, a special agency under the United Nations, and their Evangelions, giant machines capable of defeating the Angels who herald Earth's ruin. Gendou Ikari, head of the organization, seeks compatible pilots who can synchronize with the Evangelions and realize their true potential. Aiding in this defensive endeavor are talented personnel Misato Katsuragi, Head of Tactical Operations, and Ritsuko Akagi, Chief Scientist. Face to face with his father for the first time in years, 14-year-old Shinji Ikari's average life is irreversibly changed when he is whisked away into the depths of Nerv, and into a harrowing new destiny—he must become the pilot of Evangelion Unit-01 with the fate of mankind on his shoulders. Written by Hideaki Anno, Neon Genesis Evangelion is a heroic tale of a young boy who will become a legend. But as this psychological drama unfolds, ancient secrets beneath the big picture begin to bubble to the surface..."

var evangelionEpisode1 = "Nel 2015, quindici anni dopo il primo disastroso contatto con degli esseri misteriosi conosciuti come Angeli, che ha portato ad un cataclisma globale denominato Second Impact, l'umanità viene nuovamente minacciata dall'attacco di questi esseri. Per difendere il genere umano, le Nazioni Unite hanno istituito l'agenzia speciale Nerv e ne ha affidato il comando a Gendō Ikari. Questi, insieme al personale della Nerv, ha sviluppato gli Evangelion, dei giganteschi umanoidi bio-meccanici pilotabili da soggetti appositamente selezionati, tutti adolescenti orfani di madre. Shinji Ikari, il figlio del direttore abbandonato dieci anni prima all'epoca della morte della madre, è uno di questi e viene pertanto richiamato dal padre tramite il capitano Misato Katsuragi con lo scopo di fargli pilotare l'Eva-01. Nel frattempo, il terzo Angelo Sachiel attacca la città di Neo Tokyo-3 e le controffensive militari tradizionali non riescono ad arrestarlo. Inizialmente riottoso e pieno di rancore nei confronti di Gendō, Shinji si rifiuta di guidare il mezzo, ma la vista di Rei Ayanami, pilota dell'Unità 00 che sarebbe stata schierata al suo posto per la missione, ferita e agonizzante, lo convince ad affrontare l'Angelo."

var evangelionEpisode2 = "Shinji si risveglia in un letto d'ospedale, senza più alcun ricordo di quanto è avvenuto durante la lotta contro l'Angelo Sachiel svoltasi la sera precedente. Il padre Gendō, che continua a mantenere nei suoi confronti un gelido distacco, delega a Misato il compito di fargli da tutrice legale. La donna — che si rivela essere la direttrice del Reparto Operativo della Nerv — lo accoglie nel proprio appartamento, nella periferia di Neo Tokyo-3. La sera del suo arrivo, sdraiato nel letto della sua nuova stanza con le cuffiette alle orecchie, a Shinji torna di colpo alla mente tutto quello che è accaduto il giorno prima. L'Eva era stato rapidamente sconfitto dall'avversario e Shinji si trovava svenuto al suo interno quando questi ha iniziato all'improvviso a combattere autonomamente in modalità Berserk, annientando l'avversario."
